font_family      VictorMono Nerd Font 

font_size 16

adjust_line_height  150%
modify_font strikethrough_position 12px

symbol_map U+f101-U+f27d nonicons

modify_font underline_position 3
modify_font underline_thickness 150%

cursor_shape beam

cursor_blink_interval 0
scrollback_lines 20000

#: }}}
#: Mouse {{{

#: The modifier keys to press when clicking with the mouse on URLs to
#: open the URL
open_url_modifiers cmd

#: }}}
#: Terminal bell {{{

#: Enable/disable the audio bell. Useful in environments that require
#: silence.
enable_audio_bell no

#: }}}
#: Window layout {{{

#: The enabled window layouts. A comma separated list of layout names.
#: The special value all means all layouts. The first listed layout
#: will be used as the startup layout. For a list of available
#: layouts, see the
#: https://sw.kovidgoyal.net/kitty/index.html#layouts.
enabled_layouts Splits,Stack

#: Draw only the minimum borders needed. This means that only the
#: minimum needed borders for inactive windows are drawn. That is only
#: the borders that separate the inactive window from a neighbor. Note
#: that setting a non-zero window margin overrides this and causes all
#: borders to be drawn.
draw_minimal_borders yes

#: Fade the text in inactive windows by the specified amount (a number
#: between zero and one, with zero being fully faded).
inactive_text_alpha 0.8
#: }}}
#: Color scheme {{{

# Import the color theme
include ./theme.conf
background_opacity 0.2
background_blur 25

